### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamnaz** [dev0p0/BitcoinCrack#4]
python BCracker.py
Traceback (most recent call last):
  File "BCracker.py", line 40, in <module>
    private_key_hex = Generate_Private_key_hex()
  File "BCracker.py", line 21, in Generate_Private_key_hex
    ln = xchoicesx[os.urandom(1)[0]]
TypeError: list indices must be integers, not str

**Comment by SatoshiNakamotoBitcoins** [comment]
@hamnaz run it with python3...and it will work...

**Comment by dev0p0** [comment]
@SatoshiNakamotoBitcoins Thank you, yes this is a python3 script, also @hamnaz  you should have bitcoin installed using "pip install bitcoin"!
